### ISSUE TITLE
The rmagick not install in Windows7 64bit rails 4.2.0 and ruby 2.1.5

### ISSUE THREAD

**Issue by genivalvb** [gemhome/rmagick#165]
I'm try to install rmagick 2.13.4 in my Windows 7-64Bits with Ruby 2.1.5 + Rails 4.2.0 because I'm reading the ebook "Rails 4 Application Development", but not work, the message is in image below.
Could you to help me please?

![image](https://cloud.githubusercontent.com/assets/1072339/6031959/c104aac2-abea-11e4-879b-402c25865533.png)

**Comment by genivalvb** [comment]
I'm yet did install the "ImageMagick" but not work the install of rmagick.

**Comment by u338steven** [comment]
It seems like missing ```convert``` command.

1. Set ImageMagick to be first in your system path:

  ```sh
  path=[path to ImageMagick];%path%
  ```
  e.g.
  ```sh
  path=C:\Program Files\ImageMagick-6.9.0-4-Q16;%path%
  ```

2. Install the rmagick gem. You can get rmagick to compile on Windows with the command:

  ```sh
  gem install rmagick -- '--with-opt-dir="[path to ImageMagick]"'
  ```
  e.g.
  ```sh
  gem install rmagick -- '--with-opt-dir="C:\Program Files\ImageMagick-6.9.0-4-Q16"'
  ```

<cite>[Installing on Windows · rmagick/rmagick Wiki](https://github.com/rmagick/rmagick/wiki/Installing-on-Windows)</cite>

**Comment by genivalvb** [comment]
Yeah, solved

Thank you for answer u338steven

**Comment by u338steven** [comment]
You are welcome! :)
