### ISSUE TITLE
Support -Werror=format-security

### ISSUE THREAD

**Issue by mtasaka** [gemhome/rmagick#166]
When compiling source on distro, Ubuntu has "-Wformat-security" compiler option by default. Fedora even has "-Werror=format-security" and on Fedora (21) compiling rmagick 2.13.4 fails like
```
rmutil.c:1612:5: error: format not a string literal and no format arguments [-Werror=format-security]
     rb_raise(Class_FatalImageMagickError, GetLocaleExceptionMessage(severity, reason));
     ^
rmutil.c: In function 'handle_exception':
rmutil.c:1652:9: error: format not a string literal and no format arguments [-Werror=format-security]
         rb_warning(msg);
         ^
cc1: some warnings being treated as errors
```

Please apply the following patch, thank you.
http://pkgs.fedoraproject.org/cgit/rubygem-rmagick.git/tree/RMagick-2.13.1-format-security.patch

**Comment by mtasaka** [comment]
Thank you!

**Comment by vassilevsky** [comment]
Thank *you* for the patch!
