### ISSUE TITLE
Magick::QuantumDepth is now missing

### ISSUE THREAD

**Issue by carsonreinke** [gemhome/rmagick#167]
Not sure if this constant was deprecated or accidentally removed.  Present in 2.13.3, but not in 2.13.4.

```
$> gem 'rmagick', '=2.13.3'
 => true 
$> require 'rmagick'
 => true 
$> Magick::QuantumDepth
 => 8 
```
```
$> gem 'rmagick', '=2.13.4'
 => true 
$> require 'rmagick'
 => true 
$> Magick::QuantumDepth
NameError: uninitialized constant Magick::QuantumDepth
```

**Comment by carsonreinke** [comment]
Oh, looks like defined as `Magick::MAGICKCORE_QUANTUM_DEPTH` now in https://github.com/gemhome/rmagick/commit/363e4e5249ea749ec74253dfe91650a7eb131e71, might of been intentional.

**Comment by u338steven** [comment]
As you say, ```QuantumDepth``` was deprecated and replaced with ```MAGICKCORE_QUANTUM_DEPTH```.
Please use ```MAGICKCORE_QUANTUM_DEPTH``` :)
