### ISSUE TITLE
Release v2.14.0

### ISSUE THREAD

**Issue by vassilevsky** [gemhome/rmagick#183]
Hello everyone :)

Many changes have been merged to master since version 2.13.4. They need to get to users in the form of a release.

I created a new milestone if that helps:

https://github.com/gemhome/rmagick/milestones/v2.14.0

We can put stuff that needs to be done in that milestone and when it's done then make the release.

What do we need to do?

- [ ] Make it run on 1.8
- [x] Update the changelog
- [ ] ???

**Comment by bf4** [comment]
I'll take a look at it over the weekend.  @vassilevsky Do you want gem push?

**Comment by vassilevsky** [comment]
Sure, I can do that. My RubyGems username is the same.

**Comment by bf4** [comment]
>
Actually i need your rg email

**Comment by vassilevsky** [comment]
vassilevsky@gmail.com

**Comment by bf4** [comment]
done

**Comment by vassilevsky** [comment]
I have released version 2.14.0

https://rubygems.org/gems/rmagick
