### ISSUE TITLE
heroku deploy problem. 

### ISSUE THREAD

**Issue by Javingka** [gemhome/rmagick#197]
I'v been a lot of hours trying to solve this, and i just can't.

rmagick is working in my local machine, but when I deploy to Heroku, I get an application error.
I got
`require': No such file to load -- rmagick (LoadError)
and
: [3] ! Unable to load application: LoadError: No such file to load -- rmagick

I found several places with similar problems, but not the same, and I can't solve this. 
I hope to find some light about this.

thanks.

**Comment by vassilevsky** [comment]
Hello Javier :)

What does `bundle list | grep rmagick` tell you? What version of the gem you are using?

If it's older than 2.13.4, then `require 'rmagick'` simply does not work. There were simply no file named `rmagick.rb` in the old gem.

In this case, you need to write `require 'RMagick'`. In your `Gemfile`, you can write:

```ruby
gem 'rmagick', require: 'RMagick'
```

Also you can `bundle update rmagick` and then `require 'rmagick'` will work.

Please let us know if this helps.

**Comment by Javingka** [comment]
Hello  Vassilevsky and thanks for your answer.

This is embarrassing, but after take a rest. I saw the problem. I had wrote a test.rb file to test the code I needed with rmagic. I left this file in the assets/images folder, and forgot it. That was causing the problem, and for some reason the app worked in my local machine but not when deployed at heroku.

So, it just fine right now. thanks any way!.

**Comment by vassilevsky** [comment]
Glad it worked :) Please have enough rest at all times. This is important for health!
