### ISSUE TITLE
Prevent failure when "prefix" is empty string.

### ISSUE THREAD

**Issue by bf4** [gemhome/rmagick#43]
<a href="https://github.com/voxik"><img src="https://avatars.githubusercontent.com/u/14406?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [voxik](https://github.com/voxik)**
_Monday Mar 11, 2013 at 16:33 GMT_
_Originally opened as https://github.com/rmagick/rmagick/pull/71_

----

In case that "prefix" is empty string, the config_string returns false. Default to empty string for that case.

----

_**[voxik](https://github.com/voxik)** included the following code: https://github.com/rmagick/rmagick/pull/71/commits_

**Comment by vassilevsky** [comment]
@voxik I pushed your change to master. Further contributions will also be welcome.
