### ISSUE TITLE
Support "-alpha remove" to "flatten" the alpha channel

### ISSUE THREAD

**Issue by bf4** [gemhome/rmagick#63]
<a href="https://github.com/tstirrat"><img src="https://avatars.githubusercontent.com/u/702990?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tstirrat](https://github.com/tstirrat)**
_Wednesday May 21, 2014 at 21:24 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/103_

----

RMagick appears to support most of the options for `img.alpha(type)`, but it doesn't support the **alpha remove** command.

from: http://www.imagemagick.org/Usage/masking/#remove

"The best solution is to use the [Alpha Remove](http://www.imagemagick.org/Usage/masking/#alpha_remove) method to quickly and simply replace the transparency with a background color underlay..."

```
convert a.png   -background skyblue  -alpha remove -alpha off a_remove.jpg
```

At the moment I resort to a workaround:

```ruby
img.border!(0, 0, 'white')
img.alpha Magick::DeactivateAlphaChannel
```

**Comment by ollie** [comment]
:+1:  For that flag, just needed it. Thanks for the workaround, too.

**Comment by vassilevsky** [comment]
Could you add it to RMagick source code and create a pull request with it?

**Comment by ollie** [comment]
I can certainly give it a try. :smile:
