### ISSUE TITLE
Removed the SplineInterpolatePixel check

### ISSUE THREAD

**Issue by bf4** [gemhome/rmagick#8]
<a href="https://github.com/joshk"><img src="https://avatars.githubusercontent.com/u/8701?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [joshk](https://github.com/joshk)**
_Tuesday Sep 07, 2010 at 19:35 GMT_
_Originally opened as https://github.com/rmagick/rmagick/pull/15_

----

Hi Guys,

In a commit in [June 2009]( http://github.com/rmagick/rmagick/commit/da5a4001319ab6ec2823b3e117b1b501299aeb8f) a check in the extension config was removed relating to SplineInterpolatePixel and InterpolatePixelMethod. I noticed, after a fair bit of hunting, that the check regarding this enum was not removed in the rmmain.c file, so in the end SplineInterpolatePixel is never made available.

Here is a small patch which removes the check and makes SplineInterpolatePixel available for all :)

Thanks for the great gem!

Josh

----

_**[joshk](https://github.com/joshk)** included the following code: https://github.com/rmagick/rmagick/pull/15/commits_

**Comment by vassilevsky** [comment]
@joshk I pushed your commit to master:

https://github.com/gemhome/rmagick/commit/8ba470286437968603da2e13fbeed5debe0e2721

Thank you!

```
export HAS_JOSH_K_SEAL_OF_APPROVAL=true
```

**Comment by joshk** [comment]
O M G, that PR was sooooo old, 2010!!! WOW!!!!

**Comment by joshk** [comment]
Thank you :)
